---

- name: Create directory for docker-compose setup
  file:
    path: "{{ FORC_INSTALLATION_PATH }}/forc"
    state: directory
    mode: '0755'

- name: Generate .env file for forc
  template:
    src: forc.env.j2
    dest: "{{ FORC_INSTALLATION_PATH }}/forc/.env"

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: "{{ FORC_INSTALLATION_PATH }}/forc/docker-compose.yml"

- name: Override Docker image tag if provided
  replace:
    path: "{{ FORC_INSTALLATION_PATH }}/forc/docker-compose.yml"
    regexp: 'image: oci.bi.denbi.de/simplevm/forc:.*'
    replace: 'image: oci.bi.denbi.de/simplevm/forc:{{ FORC_IMAGE_TAG }}'
  when: FORC_IMAGE_TAG != ""

- name: Log into Docker registry
  community.docker.docker_login:
    registry_url: oci.bi.denbi.de
    username: "{{ OCI_USERNAME }}"
    password: "{{ OCI_TOKEN }}"
    reauthorize: true


- name: Start forc container
  community.docker.docker_compose_v2:
    project_src: "{{ FORC_INSTALLATION_PATH }}/forc"
    state: present
    wait: yes
