---
- name: Update and upgrade all packages to the latest version
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common

- name: Create directory for Docker's GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Print architecture variables
  ansible.builtin.debug:
    msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker
    state: present
  vars:
    arch_mapping:
      x86_64: amd64

- name: Install Docker and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - docker-buildx-plugin
    - docker-compose-plugin


- name: Install Docker
  apt:
    name: docker.io
    state: present
  tags: install

- name: Configure Docker
  copy:
    content: |-
             {
                "mtu":{{ ansible_default_ipv4.mtu }}
             }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0o644"

- name: Restart Docker Service
  systemd:
    name: docker
    state: restarted

- name: Create docker group and change GID
  group:
    name: docker
    gid: 1234
    state: present

- name: Append ubuntu user to group docker
  user:
    name: ubuntu
    append: true
    groups: docker

- name: (Re-)start docker socket
  systemd:
    name: docker.socket
    state: restarted

- name: Create forc backup host folder
  file:
    state: directory
    path: "{{ FORC_BACKUP_HOST_PATH }}"
    recurse: yes

- name: Copy Backup files
  copy:
    src: "{{ role_path }}/files"
    dest: "/persistent"

- name: Run the backup-forc container
  shell: |
    docker ps -q --filter name=backup-forc && docker stop backup-forc && docker rm backup-forc
    docker run -d \
      --name backup-forc \
      --restart always \
      -v "{{ FORC_BACKEND_PATH }}:/backends" \
      -v "{{ FORC_TEMPLATE_PATH }}:/templates" \
      -v "/persistent/files/install-packages.sh:/install-packages.sh" \
      -v "/persistent/files/backup.sh:/etc/cronscripts/backup.sh" \
      -v "/persistent/files/backup-cron:/etc/crontabs/dockercron/backup-cron" \
      -v "{{ FORC_BACKUP_HOST_PATH }}:/etc/backup" \
      -e BACKUP_ROTATION_ENABLED={{ FORC_BACKUP_ROTATION_ENABLED }} \
      -e BACKUP_ROTATION_MAX_SIZE={{ FORC_BACKUP_ROTATION_MAX_SIZE }} \
      -e BACKUP_ROTATION_CUT_SIZE={{ FORC_BACKUP_ROTATION_CUT_SIZE }} \
      -e BACKUP_ROTATION_SIZE_TYP={{ FORC_BACKUP_ROTATION_SIZE_TYP }} \
      quay.io/denbicloud/cron-backup:0.14.3
  args:
    executable: /bin/bash





